/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9 */

#ifndef PB_LED_CONTROL_LED_CONTROL_PB_H_INCLUDED
#define PB_LED_CONTROL_LED_CONTROL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* 设备类型：描述灯带驱动方式和通道数 */
typedef enum _led_control_DeviceType {
    led_control_DeviceType_TYPE_UNKNOWN = 0, /* 未知 / 未配置 */
    led_control_DeviceType_RGB_PWM = 1, /* 3 路 PWM（R, G, B） */
    led_control_DeviceType_RGBW_PWM = 2, /* 4 路 PWM（R, G, B, 白光 W） */
    led_control_DeviceType_RGBCW_PWM = 3, /* 5 路 PWM（R, G, B, 冷白, 暖白） */
    led_control_DeviceType_RGB_IC = 4, /* 可寻址 IC 灯带，3 通道 / 灯珠 */
    led_control_DeviceType_RGBW_IC = 5, /* 可寻址 IC 灯带，4 通道 / 灯珠 */
    led_control_DeviceType_RGBCW_IC = 6 /* 可寻址 IC 灯带，5 通道 / 灯珠（RGB + 冷白 + 暖白） */
} led_control_DeviceType;

/* 颜色模式：当前静态输出是 RGB 还是色温（CCT） */
typedef enum _led_control_ColorMode {
    led_control_ColorMode_COLOR_MODE_RGB = 0, /* 仅RGB通道工作 */
    led_control_ColorMode_COLOR_MODE_CCT = 1, /* 仅白光/色温通道工作 */
    led_control_ColorMode_COLOR_MODE_MIXED = 2 /* RGB与白光同时工作(仅RGBW/RGBCCT硬件支持) */
} led_control_ColorMode;

/* 物理输出端口的工作模式 */
typedef enum _led_control_ChannelMode {
    led_control_ChannelMode_CHANNEL_NONE = 0, /* 该端口未使用 */
    led_control_ChannelMode_CHANNEL_PWM = 1, /* 输出 PWM */
    led_control_ChannelMode_CHANNEL_IC = 2 /* 作为 IC 数据帧中的一个通道 */
} led_control_ChannelMode;

/* 预置动态效果列表 */
typedef enum _led_control_DynamicEffect {
    led_control_DynamicEffect_EFFECT_NONE = 0, /* 无效果 / 停止 */
    led_control_DynamicEffect_EFFECT_BREATH = 1, /* 呼吸灯 */
    led_control_DynamicEffect_EFFECT_RAINBOW = 2, /* 彩虹渐变 */
    led_control_DynamicEffect_EFFECT_COLOR_WIPE = 3, /* 色彩逐点填充 */
    led_control_DynamicEffect_EFFECT_THEATER_CHASE = 4, /* 剧院追逐 */
    led_control_DynamicEffect_EFFECT_COMET = 5, /* 流星拖尾 */
    led_control_DynamicEffect_EFFECT_FIRE = 6, /* 火焰模拟 */
    led_control_DynamicEffect_EFFECT_TWINKLE = 7, /* 随机闪烁 */
    led_control_DynamicEffect_EFFECT_FLOWING = 8, /* 流水灯 */
    led_control_DynamicEffect_EFFECT_BREATHE_MULTI = 9 /* 多色呼吸 */
} led_control_DynamicEffect;

/* 自定义场景中单个段内的特效模式 */
typedef enum _led_control_SegmentEffect {
    led_control_SegmentEffect_SEGMENT_STATIC = 0, /* 静态颜色 */
    led_control_SegmentEffect_SEGMENT_BREATH = 1, /* 呼吸 */
    led_control_SegmentEffect_SEGMENT_FLOW_FORWARD = 2 /* 向前流动 */
} led_control_SegmentEffect;

/* 统一错误码 */
typedef enum _led_control_ErrorCode {
    led_control_ErrorCode_OK = 0, /* 成功 */
    led_control_ErrorCode_ERR_UNKNOWN = 1, /* 未知错误 */
    led_control_ErrorCode_ERR_INVALID_PARAM = 2, /* 参数不合法 */
    led_control_ErrorCode_ERR_NOT_SUPPORTED = 3, /* 当前硬件不支持该操作 */
    led_control_ErrorCode_ERR_BUSY = 4, /* 设备忙（如正在 OTA） */
    led_control_ErrorCode_ERR_TIMEOUT = 5, /* 操作超时 */
    led_control_ErrorCode_ERR_STORAGE_FULL = 6, /* 存储空间不足（保存场景时） */
    led_control_ErrorCode_ERR_PERMISSION = 7, /* 权限不足 / 确认码错误 */
    /* OTA 专用错误码 (100 - 199) */
    led_control_ErrorCode_ERR_OTA_ALREADY_STARTED = 100, /* 已经开始了 OTA 流程 */
    led_control_ErrorCode_ERR_OTA_NOT_STARTED = 101, /* 未开始 OTA 却收到了数据块 */
    led_control_ErrorCode_ERR_OTA_CHECKSUM = 102, /* 整包校验失败 */
    led_control_ErrorCode_ERR_OTA_SIZE = 103, /* 固件大小不匹配 */
    led_control_ErrorCode_ERR_OTA_WRITE_FLASH = 104 /* 写 Flash 失败 */
} led_control_ErrorCode;

typedef enum _led_control_SceneOp {
    led_control_SceneOp_SCENE_OP_SAVE = 0, /* 保存场景到设备 */
    led_control_SceneOp_SCENE_OP_DELETE = 1, /* 删除已保存的场景 */
    led_control_SceneOp_SCENE_OP_RUN = 2, /* 运行场景（可运行已保存的或临时场景） */
    led_control_SceneOp_SCENE_OP_STOP = 3 /* 停止自定义场景，回到静态模式 */
} led_control_SceneOp;

typedef enum _led_control_OTARequest_Cmd {
    led_control_OTARequest_Cmd_CMD_START = 0, /* 开始升级，携带 OTAStartParams */
    led_control_OTARequest_Cmd_CMD_DATA = 1, /* 传输数据块，携带 OTADataParams */
    led_control_OTARequest_Cmd_CMD_COMPLETE = 2, /* 传输完成，请求校验并切换分区 */
    led_control_OTARequest_Cmd_CMD_ABORT = 3 /* 中止升级 */
} led_control_OTARequest_Cmd;

/* Struct definitions */
/* RGB 颜色值 */
typedef struct _led_control_ColorRGB {
    uint32_t r; /* 红色分量，0 - 255 */
    uint32_t g; /* 绿色分量，0 - 255 */
    uint32_t b; /* 蓝色分量，0 - 255 */
} led_control_ColorRGB;

/* 色温定义（绝对温度） */
typedef struct _led_control_ColorTemperature {
    uint32_t temperature_k; /* 色温值，单位开尔文，通常 2000 - 7000 K */
} led_control_ColorTemperature;

/* 硬件配置（可变，掉电保存） */
typedef struct _led_control_LightConfig {
    led_control_DeviceType device_type; /* 灯带类型 */
    /* 颜色通道顺序校准数组。
 索引固定：0=红, 1=绿, 2=蓝, 3=暖白, 4=冷白。
 值代表该通道在 IC 数据中的字节位置（0~4），255 表示无此通道。
 仅 IC 类型灯带有效；PWM 类型忽略。 */
    pb_size_t color_order_count;
    uint32_t color_order[5];
    uint32_t led_count; /* 灯带上的 LED / IC 数量 */
} led_control_LightConfig;

/* 设备只读属性，固件编译时确定 */
typedef struct _led_control_DeviceInfo {
    char device_name[33]; /* 蓝牙广播名 / 设备标识 */
    char fw_version[17]; /* 固件版本，如 "2.1.0" */
    char hw_version[17]; /* 硬件版本 */
    char manufacturer[33]; /* 制造商 */
    led_control_DeviceType device_type; /* 当前硬件类型（冗余，方便不拉取 config 时查看） */
    uint32_t led_count; /* 当前生效的灯珠数 */
    uint32_t max_led_count; /* 固件支持的最大灯珠数（用于 App 端输入校验） */
    uint32_t max_rgb_brightness; /* RGB 通道最大亮度值（如 255） */
    uint32_t max_white_brightness; /* 白光通道最大亮度值 */
    uint32_t min_color_temp_k; /* 支持的最低色温（K） */
    uint32_t max_color_temp_k; /* 支持的最高色温（K） */
    uint32_t max_custom_scenes; /* 可存储的自定义场景数量上限 */
} led_control_DeviceInfo;

/* 静态模式下的状态（当处于静态发光时有效） */
typedef struct _led_control_StaticState {
    bool power; /* 总开关 */
    uint32_t brightness; /* 全局亮度 0 - 100 */
    /* App应根据此字段决定高亮RGB控件还是色温控件 */
    led_control_ColorMode color_mode;
    /* 当color_mode为RGB或MIXED时有效 */
    bool has_rgb;
    led_control_ColorRGB rgb;
    /* 当color_mode为CCT或MIXED时有效 */
    bool has_cct;
    led_control_ColorTemperature cct;
    /* 【新增】独立白光亮度 0-100
 仅RGBW/RGBCCT设备有效，RGB设备始终为0
 解决"切到白光模式后亮度突变"的体验问题 */
    bool has_white_brightness;
    uint32_t white_brightness;
} led_control_StaticState;

/* 预置动态场景运行参数 */
typedef struct _led_control_PresetEffect {
    led_control_DynamicEffect scene_id; /* 预置场景 ID */
    uint32_t speed; /* 运行速度 1 - 100 */
} led_control_PresetEffect;

/* 自定义场景中的一个段 */
typedef struct _led_control_SegmentConfig {
    uint32_t start_index; /* 起始 LED 索引（0-based） */
    uint32_t end_index; /* 结束 LED 索引（包含） */
    pb_size_t which_mode;
    union {
        led_control_ColorRGB solid_color; /* 本段为静态颜色 */
        led_control_SegmentEffect effect; /* 本段为动态效果 */
    } mode;
} led_control_SegmentConfig;

/* 用户自定义的完整场景定义 */
typedef struct _led_control_CustomScene {
    uint32_t scene_id; /* 场景唯一 ID（0 - 255） */
    char name[33]; /* 场景名称（最长32字节，UTF-8） */
    uint32_t segment_count; /* 分段数目 */
    pb_size_t segments_count;
    led_control_SegmentConfig segments[10]; /* 分段列表（最多 10 段） */
    uint32_t global_speed; /* 全局速度 1 - 100 */
} led_control_CustomScene;

/* 设备完整状态快照（用于同步）
 使用 oneof current_effect 表达当前运行模式（三选一） */
typedef struct _led_control_DeviceStatus {
    pb_size_t which_current_effect;
    union {
        led_control_StaticState static_state; /* 静态模式 */
        led_control_PresetEffect preset_effect; /* 预置动态场景 */
        led_control_CustomScene custom_scene; /* 自定义场景 */
    } current_effect;
} led_control_DeviceStatus;

/* 获取设备信息（启动时首条请求，一次返回设备能力、配置和状态） */
typedef struct _led_control_GetDeviceInfoRequest {
    char dummy_field;
} led_control_GetDeviceInfoRequest;

typedef struct _led_control_GetDeviceInfoResponse {
    bool has_info;
    led_control_DeviceInfo info; /* 只读信息 */
    bool has_config;
    led_control_LightConfig config; /* 当前硬件配置 */
    bool has_status;
    led_control_DeviceStatus status; /* 运行时状态 */
} led_control_GetDeviceInfoResponse;

/* 修改硬件配置 */
typedef struct _led_control_SetLightConfigRequest {
    bool has_config;
    led_control_LightConfig config;
} led_control_SetLightConfigRequest;

typedef struct _led_control_SetLightConfigResponse {
    led_control_ErrorCode error; /* 操作结果 */
    char error_msg[65]; /* 错误原因描述 */
    bool restart_required; /* 是否需要重启设备才能生效 */
} led_control_SetLightConfigResponse;

/* 设置自定义颜色通道顺序（覆盖常见预设） */
typedef struct _led_control_SetCustomChannelOrderRequest {
    /* 5 元素数组 [红位置, 绿位置, 蓝位置, 暖白位置, 冷白位置]
 取值 0-4 或 255（无此通道） */
    pb_callback_t order;
} led_control_SetCustomChannelOrderRequest;

typedef struct _led_control_SetCustomChannelOrderResponse {
    led_control_ErrorCode error;
    char error_msg[65];
} led_control_SetCustomChannelOrderResponse;

/* 扫描 IC 灯带上的芯片数量 */
typedef struct _led_control_ScanIcRequest {
    char dummy_field;
} led_control_ScanIcRequest;

typedef struct _led_control_IcScanResult {
    uint32_t ic_count; /* 扫描到的 IC 数量，0 表示扫描失败 */
} led_control_IcScanResult;

/* 设置每个物理端口的工作模式 */
typedef struct _led_control_SetChannelModeRequest {
    led_control_ChannelMode r_mode; /* R 端口模式 */
    led_control_ChannelMode g_mode; /* G 端口模式 */
    led_control_ChannelMode b_mode; /* B 端口模式 */
    led_control_ChannelMode ww_mode; /* WW 端口模式 */
    led_control_ChannelMode cw_mode; /* CW 端口模式 */
} led_control_SetChannelModeRequest;

typedef struct _led_control_SetChannelModeResponse {
    led_control_ErrorCode error;
    char error_msg[65];
} led_control_SetChannelModeResponse;

/* 总开关 */
typedef struct _led_control_SetOnOffRequest {
    bool power; /* true = 开，false = 关 */
} led_control_SetOnOffRequest;

typedef struct _led_control_SetOnOffResponse {
    led_control_ErrorCode error;
} led_control_SetOnOffResponse;

/* 全局亮度调节 */
typedef struct _led_control_SetBrightnessRequest {
    uint32_t brightness; /* 亮度 0 - 100 */
} led_control_SetBrightnessRequest;

typedef struct _led_control_SetBrightnessResponse {
    led_control_ErrorCode error;
} led_control_SetBrightnessResponse;

/* 设置颜色 / 色温 */
typedef struct _led_control_SetColorRequest {
    led_control_ColorMode mode; /* 目标颜色模式 */
    bool has_rgb;
    led_control_ColorRGB rgb; /* mode=RGB/MIXED时使用 */
    bool has_cct;
    led_control_ColorTemperature cct; /* mode=CCT/MIXED时使用 */
    bool has_brightness;
    uint32_t brightness; /* 可选：同步修改全局亮度 */
    bool has_white_brightness;
    uint32_t white_brightness; /* 【新增】可选：同步修改白光亮度 */
} led_control_SetColorRequest;

typedef struct _led_control_SetColorResponse {
    led_control_ErrorCode error;
} led_control_SetColorResponse;

/* 批量静态模式设置（一次性下发开关、亮度、颜色） */
typedef struct _led_control_SetStaticModeRequest {
    bool power; /* 开关 */
    uint32_t brightness; /* 亮度 0 - 100 */
    led_control_ColorMode mode; /* 颜色模式 */
    pb_size_t which_color;
    union {
        led_control_ColorRGB rgb; /* RGB 颜色 */
        led_control_ColorTemperature cct; /* 色温值 */
    } color;
    /* 【新增】独立白光亮度，仅当device_type支持白光时有效
 若未填写，固件应保持上次白光亮度不变 */
    bool has_white_brightness;
    uint32_t white_brightness;
} led_control_SetStaticModeRequest;

typedef struct _led_control_SetStaticModeResponse {
    led_control_ErrorCode error;
} led_control_SetStaticModeResponse;

/* 启动一个预置动态效果 */
typedef struct _led_control_SetPresetEffectRequest {
    led_control_DynamicEffect effect; /* 效果 ID */
    uint32_t speed; /* 速度 1 - 100 */
    uint32_t brightness; /* 全局亮度 0 - 100（本次效果运行时的亮度） */
} led_control_SetPresetEffectRequest;

typedef struct _led_control_SetPresetEffectResponse {
    led_control_ErrorCode error;
} led_control_SetPresetEffectResponse;

typedef struct _led_control_SceneOperationRequest {
    led_control_SceneOp op; /* 操作类型 */
    uint32_t scene_id; /* 目标场景 ID */
    bool has_scene;
    led_control_CustomScene scene; /* 场景完整定义（SAVE / RUN 临时场景时携带） */
} led_control_SceneOperationRequest;

typedef struct _led_control_SceneOperationResponse {
    led_control_ErrorCode error;
    char error_msg[65];
} led_control_SceneOperationResponse;

/* 获取设备上已保存的场景列表 */
typedef struct _led_control_ListScenesRequest {
    char dummy_field;
} led_control_ListScenesRequest;

typedef struct _led_control_SceneSummary {
    uint32_t id; /* 场景 ID */
    char name[33]; /* 场景名称 */
} led_control_SceneSummary;

typedef struct _led_control_ListScenesResponse {
    pb_size_t scenes_count;
    led_control_SceneSummary scenes[32];
} led_control_ListScenesResponse;

/* ---------- 状态推送（设备主动上报） ----------
 当设备状态发生变化（如物理按键触发）时，固件主动推送此消息。
 为简化实现，这里直接推送完整的 DeviceStatus；也可按 changed_fields 精细控制。 */
typedef struct _led_control_StateNotification {
    uint32_t changed_fields; /* 预留位掩码，暂不使用 */
    bool has_static_state;
    led_control_StaticState static_state;
    bool has_preset_effect;
    led_control_PresetEffect preset_effect;
    bool has_custom_scene;
    led_control_CustomScene custom_scene;
} led_control_StateNotification;

typedef struct _led_control_OTAStartParams {
    uint32_t total_size; /* 固件总字节数 */
    uint32_t chunk_size; /* App 建议的分块大小（固件可忽略） */
    uint32_t crc32; /* 整包 CRC32 校验值 */
} led_control_OTAStartParams;

typedef PB_BYTES_ARRAY_T(512) led_control_OTADataParams_chunk_t;
typedef struct _led_control_OTADataParams {
    uint32_t offset; /* 当前数据块的起始偏移地址 */
    led_control_OTADataParams_chunk_t chunk; /* 固件数据块 */
} led_control_OTADataParams;

/* OTA 请求信封（使用独立端点时也可直接发送 OTARequest） */
typedef struct _led_control_OTARequest {
    led_control_OTARequest_Cmd cmd;
    pb_size_t which_params;
    union {
        led_control_OTAStartParams start_params;
        led_control_OTADataParams data_params;
    } params;
} led_control_OTARequest;

/* OTA 响应 */
typedef struct _led_control_OTAResponse {
    led_control_ErrorCode error; /* 操作结果 */
    char error_msg[65]; /* 错误描述 */
    uint32_t received_bytes; /* 已接收字节数 */
    uint32_t total_bytes; /* 固件总字节数 */
    uint32_t percent; /* 进度百分比 0 - 100 */
    bool done; /* 传输+校验是否完成 */
} led_control_OTAResponse;

/* 保活与延迟测量 */
typedef struct _led_control_PingRequest {
    uint64_t client_timestamp; /* App 发送时的毫秒时间戳 */
} led_control_PingRequest;

typedef struct _led_control_PingResponse {
    uint64_t client_timestamp; /* 原样返回 */
    uint64_t server_timestamp; /* 固件收到时的毫秒时间戳 */
} led_control_PingResponse;

/* 恢复出厂设置 */
typedef struct _led_control_FactoryResetRequest {
    uint32_t confirm_code; /* 固定为 0x525354 (ASCII "RST")，防止误操作 */
} led_control_FactoryResetRequest;

typedef struct _led_control_FactoryResetResponse {
    led_control_ErrorCode error;
} led_control_FactoryResetResponse;

/* 统一响应信封 */
typedef struct _led_control_EnvelopeResponse {
    uint32_t request_id; /* 对应的请求 ID */
    led_control_ErrorCode error; /* 操作结果（OK 表示成功） */
    char error_msg[1024]; /* 错误时的详细描述 */
    pb_size_t which_result;
    union {
        led_control_GetDeviceInfoResponse device_info_result;
        led_control_SetLightConfigResponse set_light_config;
        led_control_SetCustomChannelOrderResponse set_channel_order;
        led_control_SetChannelModeResponse set_channel_mode_result;
        led_control_IcScanResult ic_scan_result;
        led_control_SetOnOffResponse set_on_off_result;
        led_control_SetBrightnessResponse set_brightness_result;
        led_control_SetColorResponse set_color_result;
        led_control_SetStaticModeResponse set_static_result;
        led_control_SetPresetEffectResponse set_preset_result;
        led_control_SceneOperationResponse scene_op_result;
        led_control_ListScenesResponse list_scenes_result;
        led_control_OTAResponse ota_result;
        led_control_PingResponse ping_result;
        led_control_FactoryResetResponse factory_reset_result;
    } result;
} led_control_EnvelopeResponse;

typedef struct _led_control_Envelope {
    uint32_t protocol_version; /* 协议版本号，当前为 2，用于协商 */
    uint32_t request_id; /* 请求序号，响应时原样返回，便于 App 匹配 */
    pb_size_t which_payload;
    union {
        /* ---- 查询 (10-19) ---- */
        led_control_GetDeviceInfoRequest get_device_info;
        /* ---- 配置 (20-29) ---- */
        led_control_SetLightConfigRequest set_light_config;
        led_control_SetCustomChannelOrderRequest set_channel_order;
        led_control_ScanIcRequest scan_ic;
        led_control_SetChannelModeRequest set_channel_mode;
        /* ---- 灯光控制 (30-39) ---- */
        led_control_SetOnOffRequest set_on_off;
        led_control_SetBrightnessRequest set_brightness;
        led_control_SetColorRequest set_color;
        led_control_SetStaticModeRequest set_static_mode;
        led_control_SetPresetEffectRequest set_preset_effect;
        /* ---- 自定义场景 (40-49) ---- */
        led_control_SceneOperationRequest scene_op;
        led_control_ListScenesRequest list_scenes;
        /* ---- OTA (50-59) ---- */
        led_control_OTARequest ota;
        /* ---- 系统 (60-69) ---- */
        led_control_PingRequest ping;
        led_control_FactoryResetRequest factory_reset;
        /* ---- 设备 → App ---- */
        led_control_EnvelopeResponse response; /* 统一响应 */
        led_control_StateNotification state_notify; /* 状态推送 */
    } payload;
} led_control_Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _led_control_DeviceType_MIN led_control_DeviceType_TYPE_UNKNOWN
#define _led_control_DeviceType_MAX led_control_DeviceType_RGBCW_IC
#define _led_control_DeviceType_ARRAYSIZE ((led_control_DeviceType)(led_control_DeviceType_RGBCW_IC+1))

#define _led_control_ColorMode_MIN led_control_ColorMode_COLOR_MODE_RGB
#define _led_control_ColorMode_MAX led_control_ColorMode_COLOR_MODE_MIXED
#define _led_control_ColorMode_ARRAYSIZE ((led_control_ColorMode)(led_control_ColorMode_COLOR_MODE_MIXED+1))

#define _led_control_ChannelMode_MIN led_control_ChannelMode_CHANNEL_NONE
#define _led_control_ChannelMode_MAX led_control_ChannelMode_CHANNEL_IC
#define _led_control_ChannelMode_ARRAYSIZE ((led_control_ChannelMode)(led_control_ChannelMode_CHANNEL_IC+1))

#define _led_control_DynamicEffect_MIN led_control_DynamicEffect_EFFECT_NONE
#define _led_control_DynamicEffect_MAX led_control_DynamicEffect_EFFECT_BREATHE_MULTI
#define _led_control_DynamicEffect_ARRAYSIZE ((led_control_DynamicEffect)(led_control_DynamicEffect_EFFECT_BREATHE_MULTI+1))

#define _led_control_SegmentEffect_MIN led_control_SegmentEffect_SEGMENT_STATIC
#define _led_control_SegmentEffect_MAX led_control_SegmentEffect_SEGMENT_FLOW_FORWARD
#define _led_control_SegmentEffect_ARRAYSIZE ((led_control_SegmentEffect)(led_control_SegmentEffect_SEGMENT_FLOW_FORWARD+1))

#define _led_control_ErrorCode_MIN led_control_ErrorCode_OK
#define _led_control_ErrorCode_MAX led_control_ErrorCode_ERR_OTA_WRITE_FLASH
#define _led_control_ErrorCode_ARRAYSIZE ((led_control_ErrorCode)(led_control_ErrorCode_ERR_OTA_WRITE_FLASH+1))

#define _led_control_SceneOp_MIN led_control_SceneOp_SCENE_OP_SAVE
#define _led_control_SceneOp_MAX led_control_SceneOp_SCENE_OP_STOP
#define _led_control_SceneOp_ARRAYSIZE ((led_control_SceneOp)(led_control_SceneOp_SCENE_OP_STOP+1))

#define _led_control_OTARequest_Cmd_MIN led_control_OTARequest_Cmd_CMD_START
#define _led_control_OTARequest_Cmd_MAX led_control_OTARequest_Cmd_CMD_ABORT
#define _led_control_OTARequest_Cmd_ARRAYSIZE ((led_control_OTARequest_Cmd)(led_control_OTARequest_Cmd_CMD_ABORT+1))



#define led_control_LightConfig_device_type_ENUMTYPE led_control_DeviceType

#define led_control_DeviceInfo_device_type_ENUMTYPE led_control_DeviceType

#define led_control_StaticState_color_mode_ENUMTYPE led_control_ColorMode

#define led_control_PresetEffect_scene_id_ENUMTYPE led_control_DynamicEffect

#define led_control_SegmentConfig_mode_effect_ENUMTYPE led_control_SegmentEffect






#define led_control_SetLightConfigResponse_error_ENUMTYPE led_control_ErrorCode


#define led_control_SetCustomChannelOrderResponse_error_ENUMTYPE led_control_ErrorCode



#define led_control_SetChannelModeRequest_r_mode_ENUMTYPE led_control_ChannelMode
#define led_control_SetChannelModeRequest_g_mode_ENUMTYPE led_control_ChannelMode
#define led_control_SetChannelModeRequest_b_mode_ENUMTYPE led_control_ChannelMode
#define led_control_SetChannelModeRequest_ww_mode_ENUMTYPE led_control_ChannelMode
#define led_control_SetChannelModeRequest_cw_mode_ENUMTYPE led_control_ChannelMode

#define led_control_SetChannelModeResponse_error_ENUMTYPE led_control_ErrorCode


#define led_control_SetOnOffResponse_error_ENUMTYPE led_control_ErrorCode


#define led_control_SetBrightnessResponse_error_ENUMTYPE led_control_ErrorCode

#define led_control_SetColorRequest_mode_ENUMTYPE led_control_ColorMode

#define led_control_SetColorResponse_error_ENUMTYPE led_control_ErrorCode

#define led_control_SetStaticModeRequest_mode_ENUMTYPE led_control_ColorMode

#define led_control_SetStaticModeResponse_error_ENUMTYPE led_control_ErrorCode

#define led_control_SetPresetEffectRequest_effect_ENUMTYPE led_control_DynamicEffect

#define led_control_SetPresetEffectResponse_error_ENUMTYPE led_control_ErrorCode

#define led_control_SceneOperationRequest_op_ENUMTYPE led_control_SceneOp

#define led_control_SceneOperationResponse_error_ENUMTYPE led_control_ErrorCode







#define led_control_OTARequest_cmd_ENUMTYPE led_control_OTARequest_Cmd

#define led_control_OTAResponse_error_ENUMTYPE led_control_ErrorCode




#define led_control_FactoryResetResponse_error_ENUMTYPE led_control_ErrorCode


#define led_control_EnvelopeResponse_error_ENUMTYPE led_control_ErrorCode


/* Initializer values for message structs */
#define led_control_ColorRGB_init_default        {0, 0, 0}
#define led_control_ColorTemperature_init_default {0}
#define led_control_LightConfig_init_default     {_led_control_DeviceType_MIN, 0, {0, 0, 0, 0, 0}, 0}
#define led_control_DeviceInfo_init_default      {"", "", "", "", _led_control_DeviceType_MIN, 0, 0, 0, 0, 0, 0, 0}
#define led_control_StaticState_init_default     {0, 0, _led_control_ColorMode_MIN, false, led_control_ColorRGB_init_default, false, led_control_ColorTemperature_init_default, false, 0}
#define led_control_PresetEffect_init_default    {_led_control_DynamicEffect_MIN, 0}
#define led_control_SegmentConfig_init_default   {0, 0, 0, {led_control_ColorRGB_init_default}}
#define led_control_CustomScene_init_default     {0, "", 0, 0, {led_control_SegmentConfig_init_default, led_control_SegmentConfig_init_default, led_control_SegmentConfig_init_default, led_control_SegmentConfig_init_default, led_control_SegmentConfig_init_default, led_control_SegmentConfig_init_default, led_control_SegmentConfig_init_default, led_control_SegmentConfig_init_default, led_control_SegmentConfig_init_default, led_control_SegmentConfig_init_default}, 0}
#define led_control_DeviceStatus_init_default    {0, {led_control_StaticState_init_default}}
#define led_control_GetDeviceInfoRequest_init_default {0}
#define led_control_GetDeviceInfoResponse_init_default {false, led_control_DeviceInfo_init_default, false, led_control_LightConfig_init_default, false, led_control_DeviceStatus_init_default}
#define led_control_SetLightConfigRequest_init_default {false, led_control_LightConfig_init_default}
#define led_control_SetLightConfigResponse_init_default {_led_control_ErrorCode_MIN, "", 0}
#define led_control_SetCustomChannelOrderRequest_init_default {{{NULL}, NULL}}
#define led_control_SetCustomChannelOrderResponse_init_default {_led_control_ErrorCode_MIN, ""}
#define led_control_ScanIcRequest_init_default   {0}
#define led_control_IcScanResult_init_default    {0}
#define led_control_SetChannelModeRequest_init_default {_led_control_ChannelMode_MIN, _led_control_ChannelMode_MIN, _led_control_ChannelMode_MIN, _led_control_ChannelMode_MIN, _led_control_ChannelMode_MIN}
#define led_control_SetChannelModeResponse_init_default {_led_control_ErrorCode_MIN, ""}
#define led_control_SetOnOffRequest_init_default {0}
#define led_control_SetOnOffResponse_init_default {_led_control_ErrorCode_MIN}
#define led_control_SetBrightnessRequest_init_default {0}
#define led_control_SetBrightnessResponse_init_default {_led_control_ErrorCode_MIN}
#define led_control_SetColorRequest_init_default {_led_control_ColorMode_MIN, false, led_control_ColorRGB_init_default, false, led_control_ColorTemperature_init_default, false, 0, false, 0}
#define led_control_SetColorResponse_init_default {_led_control_ErrorCode_MIN}
#define led_control_SetStaticModeRequest_init_default {0, 0, _led_control_ColorMode_MIN, 0, {led_control_ColorRGB_init_default}, false, 0}
#define led_control_SetStaticModeResponse_init_default {_led_control_ErrorCode_MIN}
#define led_control_SetPresetEffectRequest_init_default {_led_control_DynamicEffect_MIN, 0, 0}
#define led_control_SetPresetEffectResponse_init_default {_led_control_ErrorCode_MIN}
#define led_control_SceneOperationRequest_init_default {_led_control_SceneOp_MIN, 0, false, led_control_CustomScene_init_default}
#define led_control_SceneOperationResponse_init_default {_led_control_ErrorCode_MIN, ""}
#define led_control_ListScenesRequest_init_default {0}
#define led_control_ListScenesResponse_init_default {0, {led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default, led_control_SceneSummary_init_default}}
#define led_control_SceneSummary_init_default    {0, ""}
#define led_control_StateNotification_init_default {0, false, led_control_StaticState_init_default, false, led_control_PresetEffect_init_default, false, led_control_CustomScene_init_default}
#define led_control_OTAStartParams_init_default  {0, 0, 0}
#define led_control_OTADataParams_init_default   {0, {0, {0}}}
#define led_control_OTARequest_init_default      {_led_control_OTARequest_Cmd_MIN, 0, {led_control_OTAStartParams_init_default}}
#define led_control_OTAResponse_init_default     {_led_control_ErrorCode_MIN, "", 0, 0, 0, 0}
#define led_control_PingRequest_init_default     {0}
#define led_control_PingResponse_init_default    {0, 0}
#define led_control_FactoryResetRequest_init_default {0}
#define led_control_FactoryResetResponse_init_default {_led_control_ErrorCode_MIN}
#define led_control_Envelope_init_default        {0, 0, 0, {led_control_GetDeviceInfoRequest_init_default}}
#define led_control_EnvelopeResponse_init_default {0, _led_control_ErrorCode_MIN, "", 0, {led_control_GetDeviceInfoResponse_init_default}}
#define led_control_ColorRGB_init_zero           {0, 0, 0}
#define led_control_ColorTemperature_init_zero   {0}
#define led_control_LightConfig_init_zero        {_led_control_DeviceType_MIN, 0, {0, 0, 0, 0, 0}, 0}
#define led_control_DeviceInfo_init_zero         {"", "", "", "", _led_control_DeviceType_MIN, 0, 0, 0, 0, 0, 0, 0}
#define led_control_StaticState_init_zero        {0, 0, _led_control_ColorMode_MIN, false, led_control_ColorRGB_init_zero, false, led_control_ColorTemperature_init_zero, false, 0}
#define led_control_PresetEffect_init_zero       {_led_control_DynamicEffect_MIN, 0}
#define led_control_SegmentConfig_init_zero      {0, 0, 0, {led_control_ColorRGB_init_zero}}
#define led_control_CustomScene_init_zero        {0, "", 0, 0, {led_control_SegmentConfig_init_zero, led_control_SegmentConfig_init_zero, led_control_SegmentConfig_init_zero, led_control_SegmentConfig_init_zero, led_control_SegmentConfig_init_zero, led_control_SegmentConfig_init_zero, led_control_SegmentConfig_init_zero, led_control_SegmentConfig_init_zero, led_control_SegmentConfig_init_zero, led_control_SegmentConfig_init_zero}, 0}
#define led_control_DeviceStatus_init_zero       {0, {led_control_StaticState_init_zero}}
#define led_control_GetDeviceInfoRequest_init_zero {0}
#define led_control_GetDeviceInfoResponse_init_zero {false, led_control_DeviceInfo_init_zero, false, led_control_LightConfig_init_zero, false, led_control_DeviceStatus_init_zero}
#define led_control_SetLightConfigRequest_init_zero {false, led_control_LightConfig_init_zero}
#define led_control_SetLightConfigResponse_init_zero {_led_control_ErrorCode_MIN, "", 0}
#define led_control_SetCustomChannelOrderRequest_init_zero {{{NULL}, NULL}}
#define led_control_SetCustomChannelOrderResponse_init_zero {_led_control_ErrorCode_MIN, ""}
#define led_control_ScanIcRequest_init_zero      {0}
#define led_control_IcScanResult_init_zero       {0}
#define led_control_SetChannelModeRequest_init_zero {_led_control_ChannelMode_MIN, _led_control_ChannelMode_MIN, _led_control_ChannelMode_MIN, _led_control_ChannelMode_MIN, _led_control_ChannelMode_MIN}
#define led_control_SetChannelModeResponse_init_zero {_led_control_ErrorCode_MIN, ""}
#define led_control_SetOnOffRequest_init_zero    {0}
#define led_control_SetOnOffResponse_init_zero   {_led_control_ErrorCode_MIN}
#define led_control_SetBrightnessRequest_init_zero {0}
#define led_control_SetBrightnessResponse_init_zero {_led_control_ErrorCode_MIN}
#define led_control_SetColorRequest_init_zero    {_led_control_ColorMode_MIN, false, led_control_ColorRGB_init_zero, false, led_control_ColorTemperature_init_zero, false, 0, false, 0}
#define led_control_SetColorResponse_init_zero   {_led_control_ErrorCode_MIN}
#define led_control_SetStaticModeRequest_init_zero {0, 0, _led_control_ColorMode_MIN, 0, {led_control_ColorRGB_init_zero}, false, 0}
#define led_control_SetStaticModeResponse_init_zero {_led_control_ErrorCode_MIN}
#define led_control_SetPresetEffectRequest_init_zero {_led_control_DynamicEffect_MIN, 0, 0}
#define led_control_SetPresetEffectResponse_init_zero {_led_control_ErrorCode_MIN}
#define led_control_SceneOperationRequest_init_zero {_led_control_SceneOp_MIN, 0, false, led_control_CustomScene_init_zero}
#define led_control_SceneOperationResponse_init_zero {_led_control_ErrorCode_MIN, ""}
#define led_control_ListScenesRequest_init_zero  {0}
#define led_control_ListScenesResponse_init_zero {0, {led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero, led_control_SceneSummary_init_zero}}
#define led_control_SceneSummary_init_zero       {0, ""}
#define led_control_StateNotification_init_zero  {0, false, led_control_StaticState_init_zero, false, led_control_PresetEffect_init_zero, false, led_control_CustomScene_init_zero}
#define led_control_OTAStartParams_init_zero     {0, 0, 0}
#define led_control_OTADataParams_init_zero      {0, {0, {0}}}
#define led_control_OTARequest_init_zero         {_led_control_OTARequest_Cmd_MIN, 0, {led_control_OTAStartParams_init_zero}}
#define led_control_OTAResponse_init_zero        {_led_control_ErrorCode_MIN, "", 0, 0, 0, 0}
#define led_control_PingRequest_init_zero        {0}
#define led_control_PingResponse_init_zero       {0, 0}
#define led_control_FactoryResetRequest_init_zero {0}
#define led_control_FactoryResetResponse_init_zero {_led_control_ErrorCode_MIN}
#define led_control_Envelope_init_zero           {0, 0, 0, {led_control_GetDeviceInfoRequest_init_zero}}
#define led_control_EnvelopeResponse_init_zero   {0, _led_control_ErrorCode_MIN, "", 0, {led_control_GetDeviceInfoResponse_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define led_control_ColorRGB_r_tag               1
#define led_control_ColorRGB_g_tag               2
#define led_control_ColorRGB_b_tag               3
#define led_control_ColorTemperature_temperature_k_tag 1
#define led_control_LightConfig_device_type_tag  1
#define led_control_LightConfig_color_order_tag  2
#define led_control_LightConfig_led_count_tag    3
#define led_control_DeviceInfo_device_name_tag   1
#define led_control_DeviceInfo_fw_version_tag    2
#define led_control_DeviceInfo_hw_version_tag    3
#define led_control_DeviceInfo_manufacturer_tag  4
#define led_control_DeviceInfo_device_type_tag   5
#define led_control_DeviceInfo_led_count_tag     6
#define led_control_DeviceInfo_max_led_count_tag 7
#define led_control_DeviceInfo_max_rgb_brightness_tag 8
#define led_control_DeviceInfo_max_white_brightness_tag 9
#define led_control_DeviceInfo_min_color_temp_k_tag 10
#define led_control_DeviceInfo_max_color_temp_k_tag 11
#define led_control_DeviceInfo_max_custom_scenes_tag 12
#define led_control_StaticState_power_tag        1
#define led_control_StaticState_brightness_tag   2
#define led_control_StaticState_color_mode_tag   3
#define led_control_StaticState_rgb_tag          4
#define led_control_StaticState_cct_tag          5
#define led_control_StaticState_white_brightness_tag 6
#define led_control_PresetEffect_scene_id_tag    1
#define led_control_PresetEffect_speed_tag       2
#define led_control_SegmentConfig_start_index_tag 1
#define led_control_SegmentConfig_end_index_tag  2
#define led_control_SegmentConfig_solid_color_tag 3
#define led_control_SegmentConfig_effect_tag     4
#define led_control_CustomScene_scene_id_tag     1
#define led_control_CustomScene_name_tag         2
#define led_control_CustomScene_segment_count_tag 3
#define led_control_CustomScene_segments_tag     4
#define led_control_CustomScene_global_speed_tag 5
#define led_control_DeviceStatus_static_state_tag 1
#define led_control_DeviceStatus_preset_effect_tag 2
#define led_control_DeviceStatus_custom_scene_tag 3
#define led_control_GetDeviceInfoResponse_info_tag 1
#define led_control_GetDeviceInfoResponse_config_tag 2
#define led_control_GetDeviceInfoResponse_status_tag 3
#define led_control_SetLightConfigRequest_config_tag 1
#define led_control_SetLightConfigResponse_error_tag 1
#define led_control_SetLightConfigResponse_error_msg_tag 2
#define led_control_SetLightConfigResponse_restart_required_tag 3
#define led_control_SetCustomChannelOrderRequest_order_tag 1
#define led_control_SetCustomChannelOrderResponse_error_tag 1
#define led_control_SetCustomChannelOrderResponse_error_msg_tag 2
#define led_control_IcScanResult_ic_count_tag    1
#define led_control_SetChannelModeRequest_r_mode_tag 1
#define led_control_SetChannelModeRequest_g_mode_tag 2
#define led_control_SetChannelModeRequest_b_mode_tag 3
#define led_control_SetChannelModeRequest_ww_mode_tag 4
#define led_control_SetChannelModeRequest_cw_mode_tag 5
#define led_control_SetChannelModeResponse_error_tag 1
#define led_control_SetChannelModeResponse_error_msg_tag 2
#define led_control_SetOnOffRequest_power_tag    1
#define led_control_SetOnOffResponse_error_tag   1
#define led_control_SetBrightnessRequest_brightness_tag 1
#define led_control_SetBrightnessResponse_error_tag 1
#define led_control_SetColorRequest_mode_tag     1
#define led_control_SetColorRequest_rgb_tag      2
#define led_control_SetColorRequest_cct_tag      3
#define led_control_SetColorRequest_brightness_tag 4
#define led_control_SetColorRequest_white_brightness_tag 5
#define led_control_SetColorResponse_error_tag   1
#define led_control_SetStaticModeRequest_power_tag 1
#define led_control_SetStaticModeRequest_brightness_tag 2
#define led_control_SetStaticModeRequest_mode_tag 3
#define led_control_SetStaticModeRequest_rgb_tag 4
#define led_control_SetStaticModeRequest_cct_tag 5
#define led_control_SetStaticModeRequest_white_brightness_tag 6
#define led_control_SetStaticModeResponse_error_tag 1
#define led_control_SetPresetEffectRequest_effect_tag 1
#define led_control_SetPresetEffectRequest_speed_tag 2
#define led_control_SetPresetEffectRequest_brightness_tag 3
#define led_control_SetPresetEffectResponse_error_tag 1
#define led_control_SceneOperationRequest_op_tag 1
#define led_control_SceneOperationRequest_scene_id_tag 2
#define led_control_SceneOperationRequest_scene_tag 3
#define led_control_SceneOperationResponse_error_tag 1
#define led_control_SceneOperationResponse_error_msg_tag 2
#define led_control_SceneSummary_id_tag          1
#define led_control_SceneSummary_name_tag        2
#define led_control_ListScenesResponse_scenes_tag 1
#define led_control_StateNotification_changed_fields_tag 1
#define led_control_StateNotification_static_state_tag 2
#define led_control_StateNotification_preset_effect_tag 3
#define led_control_StateNotification_custom_scene_tag 4
#define led_control_OTAStartParams_total_size_tag 1
#define led_control_OTAStartParams_chunk_size_tag 2
#define led_control_OTAStartParams_crc32_tag     3
#define led_control_OTADataParams_offset_tag     1
#define led_control_OTADataParams_chunk_tag      2
#define led_control_OTARequest_cmd_tag           1
#define led_control_OTARequest_start_params_tag  10
#define led_control_OTARequest_data_params_tag   11
#define led_control_OTAResponse_error_tag        1
#define led_control_OTAResponse_error_msg_tag    2
#define led_control_OTAResponse_received_bytes_tag 3
#define led_control_OTAResponse_total_bytes_tag  4
#define led_control_OTAResponse_percent_tag      5
#define led_control_OTAResponse_done_tag         6
#define led_control_PingRequest_client_timestamp_tag 1
#define led_control_PingResponse_client_timestamp_tag 1
#define led_control_PingResponse_server_timestamp_tag 2
#define led_control_FactoryResetRequest_confirm_code_tag 1
#define led_control_FactoryResetResponse_error_tag 1
#define led_control_EnvelopeResponse_request_id_tag 1
#define led_control_EnvelopeResponse_error_tag   2
#define led_control_EnvelopeResponse_error_msg_tag 3
#define led_control_EnvelopeResponse_device_info_result_tag 10
#define led_control_EnvelopeResponse_set_light_config_tag 11
#define led_control_EnvelopeResponse_set_channel_order_tag 12
#define led_control_EnvelopeResponse_set_channel_mode_result_tag 13
#define led_control_EnvelopeResponse_ic_scan_result_tag 14
#define led_control_EnvelopeResponse_set_on_off_result_tag 20
#define led_control_EnvelopeResponse_set_brightness_result_tag 21
#define led_control_EnvelopeResponse_set_color_result_tag 22
#define led_control_EnvelopeResponse_set_static_result_tag 23
#define led_control_EnvelopeResponse_set_preset_result_tag 24
#define led_control_EnvelopeResponse_scene_op_result_tag 30
#define led_control_EnvelopeResponse_list_scenes_result_tag 31
#define led_control_EnvelopeResponse_ota_result_tag 40
#define led_control_EnvelopeResponse_ping_result_tag 50
#define led_control_EnvelopeResponse_factory_reset_result_tag 51
#define led_control_Envelope_protocol_version_tag 1
#define led_control_Envelope_request_id_tag      2
#define led_control_Envelope_get_device_info_tag 10
#define led_control_Envelope_set_light_config_tag 20
#define led_control_Envelope_set_channel_order_tag 21
#define led_control_Envelope_scan_ic_tag         22
#define led_control_Envelope_set_channel_mode_tag 23
#define led_control_Envelope_set_on_off_tag      30
#define led_control_Envelope_set_brightness_tag  31
#define led_control_Envelope_set_color_tag       32
#define led_control_Envelope_set_static_mode_tag 33
#define led_control_Envelope_set_preset_effect_tag 34
#define led_control_Envelope_scene_op_tag        40
#define led_control_Envelope_list_scenes_tag     41
#define led_control_Envelope_ota_tag             50
#define led_control_Envelope_ping_tag            60
#define led_control_Envelope_factory_reset_tag   61
#define led_control_Envelope_response_tag        80
#define led_control_Envelope_state_notify_tag    90

/* Struct field encoding specification for nanopb */
#define led_control_ColorRGB_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   r,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   g,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   b,                 3)
#define led_control_ColorRGB_CALLBACK NULL
#define led_control_ColorRGB_DEFAULT NULL

#define led_control_ColorTemperature_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   temperature_k,     1)
#define led_control_ColorTemperature_CALLBACK NULL
#define led_control_ColorTemperature_DEFAULT NULL

#define led_control_LightConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,       1) \
X(a, STATIC,   REPEATED, UINT32,   color_order,       2) \
X(a, STATIC,   SINGULAR, UINT32,   led_count,         3)
#define led_control_LightConfig_CALLBACK NULL
#define led_control_LightConfig_DEFAULT NULL

#define led_control_DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   device_name,       1) \
X(a, STATIC,   SINGULAR, STRING,   fw_version,        2) \
X(a, STATIC,   SINGULAR, STRING,   hw_version,        3) \
X(a, STATIC,   SINGULAR, STRING,   manufacturer,      4) \
X(a, STATIC,   SINGULAR, UENUM,    device_type,       5) \
X(a, STATIC,   SINGULAR, UINT32,   led_count,         6) \
X(a, STATIC,   SINGULAR, UINT32,   max_led_count,     7) \
X(a, STATIC,   SINGULAR, UINT32,   max_rgb_brightness,   8) \
X(a, STATIC,   SINGULAR, UINT32,   max_white_brightness,   9) \
X(a, STATIC,   SINGULAR, UINT32,   min_color_temp_k,  10) \
X(a, STATIC,   SINGULAR, UINT32,   max_color_temp_k,  11) \
X(a, STATIC,   SINGULAR, UINT32,   max_custom_scenes,  12)
#define led_control_DeviceInfo_CALLBACK NULL
#define led_control_DeviceInfo_DEFAULT NULL

#define led_control_StaticState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     power,             1) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        2) \
X(a, STATIC,   SINGULAR, UENUM,    color_mode,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rgb,               4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cct,               5) \
X(a, STATIC,   OPTIONAL, UINT32,   white_brightness,   6)
#define led_control_StaticState_CALLBACK NULL
#define led_control_StaticState_DEFAULT NULL
#define led_control_StaticState_rgb_MSGTYPE led_control_ColorRGB
#define led_control_StaticState_cct_MSGTYPE led_control_ColorTemperature

#define led_control_PresetEffect_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    scene_id,          1) \
X(a, STATIC,   SINGULAR, UINT32,   speed,             2)
#define led_control_PresetEffect_CALLBACK NULL
#define led_control_PresetEffect_DEFAULT NULL

#define led_control_SegmentConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_index,       1) \
X(a, STATIC,   SINGULAR, UINT32,   end_index,         2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mode,solid_color,mode.solid_color),   3) \
X(a, STATIC,   ONEOF,    UENUM,    (mode,effect,mode.effect),   4)
#define led_control_SegmentConfig_CALLBACK NULL
#define led_control_SegmentConfig_DEFAULT NULL
#define led_control_SegmentConfig_mode_solid_color_MSGTYPE led_control_ColorRGB

#define led_control_CustomScene_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   scene_id,          1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2) \
X(a, STATIC,   SINGULAR, UINT32,   segment_count,     3) \
X(a, STATIC,   REPEATED, MESSAGE,  segments,          4) \
X(a, STATIC,   SINGULAR, UINT32,   global_speed,      5)
#define led_control_CustomScene_CALLBACK NULL
#define led_control_CustomScene_DEFAULT NULL
#define led_control_CustomScene_segments_MSGTYPE led_control_SegmentConfig

#define led_control_DeviceStatus_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (current_effect,static_state,current_effect.static_state),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (current_effect,preset_effect,current_effect.preset_effect),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (current_effect,custom_scene,current_effect.custom_scene),   3)
#define led_control_DeviceStatus_CALLBACK NULL
#define led_control_DeviceStatus_DEFAULT NULL
#define led_control_DeviceStatus_current_effect_static_state_MSGTYPE led_control_StaticState
#define led_control_DeviceStatus_current_effect_preset_effect_MSGTYPE led_control_PresetEffect
#define led_control_DeviceStatus_current_effect_custom_scene_MSGTYPE led_control_CustomScene

#define led_control_GetDeviceInfoRequest_FIELDLIST(X, a) \

#define led_control_GetDeviceInfoRequest_CALLBACK NULL
#define led_control_GetDeviceInfoRequest_DEFAULT NULL

#define led_control_GetDeviceInfoResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  info,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  status,            3)
#define led_control_GetDeviceInfoResponse_CALLBACK NULL
#define led_control_GetDeviceInfoResponse_DEFAULT NULL
#define led_control_GetDeviceInfoResponse_info_MSGTYPE led_control_DeviceInfo
#define led_control_GetDeviceInfoResponse_config_MSGTYPE led_control_LightConfig
#define led_control_GetDeviceInfoResponse_status_MSGTYPE led_control_DeviceStatus

#define led_control_SetLightConfigRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config,            1)
#define led_control_SetLightConfigRequest_CALLBACK NULL
#define led_control_SetLightConfigRequest_DEFAULT NULL
#define led_control_SetLightConfigRequest_config_MSGTYPE led_control_LightConfig

#define led_control_SetLightConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, STRING,   error_msg,         2) \
X(a, STATIC,   SINGULAR, BOOL,     restart_required,   3)
#define led_control_SetLightConfigResponse_CALLBACK NULL
#define led_control_SetLightConfigResponse_DEFAULT NULL

#define led_control_SetCustomChannelOrderRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   order,             1)
#define led_control_SetCustomChannelOrderRequest_CALLBACK pb_default_field_callback
#define led_control_SetCustomChannelOrderRequest_DEFAULT NULL

#define led_control_SetCustomChannelOrderResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, STRING,   error_msg,         2)
#define led_control_SetCustomChannelOrderResponse_CALLBACK NULL
#define led_control_SetCustomChannelOrderResponse_DEFAULT NULL

#define led_control_ScanIcRequest_FIELDLIST(X, a) \

#define led_control_ScanIcRequest_CALLBACK NULL
#define led_control_ScanIcRequest_DEFAULT NULL

#define led_control_IcScanResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ic_count,          1)
#define led_control_IcScanResult_CALLBACK NULL
#define led_control_IcScanResult_DEFAULT NULL

#define led_control_SetChannelModeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    r_mode,            1) \
X(a, STATIC,   SINGULAR, UENUM,    g_mode,            2) \
X(a, STATIC,   SINGULAR, UENUM,    b_mode,            3) \
X(a, STATIC,   SINGULAR, UENUM,    ww_mode,           4) \
X(a, STATIC,   SINGULAR, UENUM,    cw_mode,           5)
#define led_control_SetChannelModeRequest_CALLBACK NULL
#define led_control_SetChannelModeRequest_DEFAULT NULL

#define led_control_SetChannelModeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, STRING,   error_msg,         2)
#define led_control_SetChannelModeResponse_CALLBACK NULL
#define led_control_SetChannelModeResponse_DEFAULT NULL

#define led_control_SetOnOffRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     power,             1)
#define led_control_SetOnOffRequest_CALLBACK NULL
#define led_control_SetOnOffRequest_DEFAULT NULL

#define led_control_SetOnOffResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1)
#define led_control_SetOnOffResponse_CALLBACK NULL
#define led_control_SetOnOffResponse_DEFAULT NULL

#define led_control_SetBrightnessRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        1)
#define led_control_SetBrightnessRequest_CALLBACK NULL
#define led_control_SetBrightnessRequest_DEFAULT NULL

#define led_control_SetBrightnessResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1)
#define led_control_SetBrightnessResponse_CALLBACK NULL
#define led_control_SetBrightnessResponse_DEFAULT NULL

#define led_control_SetColorRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  rgb,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cct,               3) \
X(a, STATIC,   OPTIONAL, UINT32,   brightness,        4) \
X(a, STATIC,   OPTIONAL, UINT32,   white_brightness,   5)
#define led_control_SetColorRequest_CALLBACK NULL
#define led_control_SetColorRequest_DEFAULT NULL
#define led_control_SetColorRequest_rgb_MSGTYPE led_control_ColorRGB
#define led_control_SetColorRequest_cct_MSGTYPE led_control_ColorTemperature

#define led_control_SetColorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1)
#define led_control_SetColorResponse_CALLBACK NULL
#define led_control_SetColorResponse_DEFAULT NULL

#define led_control_SetStaticModeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     power,             1) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        2) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (color,rgb,color.rgb),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (color,cct,color.cct),   5) \
X(a, STATIC,   OPTIONAL, UINT32,   white_brightness,   6)
#define led_control_SetStaticModeRequest_CALLBACK NULL
#define led_control_SetStaticModeRequest_DEFAULT NULL
#define led_control_SetStaticModeRequest_color_rgb_MSGTYPE led_control_ColorRGB
#define led_control_SetStaticModeRequest_color_cct_MSGTYPE led_control_ColorTemperature

#define led_control_SetStaticModeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1)
#define led_control_SetStaticModeResponse_CALLBACK NULL
#define led_control_SetStaticModeResponse_DEFAULT NULL

#define led_control_SetPresetEffectRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    effect,            1) \
X(a, STATIC,   SINGULAR, UINT32,   speed,             2) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        3)
#define led_control_SetPresetEffectRequest_CALLBACK NULL
#define led_control_SetPresetEffectRequest_DEFAULT NULL

#define led_control_SetPresetEffectResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1)
#define led_control_SetPresetEffectResponse_CALLBACK NULL
#define led_control_SetPresetEffectResponse_DEFAULT NULL

#define led_control_SceneOperationRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    op,                1) \
X(a, STATIC,   SINGULAR, UINT32,   scene_id,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  scene,             3)
#define led_control_SceneOperationRequest_CALLBACK NULL
#define led_control_SceneOperationRequest_DEFAULT NULL
#define led_control_SceneOperationRequest_scene_MSGTYPE led_control_CustomScene

#define led_control_SceneOperationResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, STRING,   error_msg,         2)
#define led_control_SceneOperationResponse_CALLBACK NULL
#define led_control_SceneOperationResponse_DEFAULT NULL

#define led_control_ListScenesRequest_FIELDLIST(X, a) \

#define led_control_ListScenesRequest_CALLBACK NULL
#define led_control_ListScenesRequest_DEFAULT NULL

#define led_control_ListScenesResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  scenes,            1)
#define led_control_ListScenesResponse_CALLBACK NULL
#define led_control_ListScenesResponse_DEFAULT NULL
#define led_control_ListScenesResponse_scenes_MSGTYPE led_control_SceneSummary

#define led_control_SceneSummary_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2)
#define led_control_SceneSummary_CALLBACK NULL
#define led_control_SceneSummary_DEFAULT NULL

#define led_control_StateNotification_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   changed_fields,    1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  static_state,      2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  preset_effect,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  custom_scene,      4)
#define led_control_StateNotification_CALLBACK NULL
#define led_control_StateNotification_DEFAULT NULL
#define led_control_StateNotification_static_state_MSGTYPE led_control_StaticState
#define led_control_StateNotification_preset_effect_MSGTYPE led_control_PresetEffect
#define led_control_StateNotification_custom_scene_MSGTYPE led_control_CustomScene

#define led_control_OTAStartParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   total_size,        1) \
X(a, STATIC,   SINGULAR, UINT32,   chunk_size,        2) \
X(a, STATIC,   SINGULAR, UINT32,   crc32,             3)
#define led_control_OTAStartParams_CALLBACK NULL
#define led_control_OTAStartParams_DEFAULT NULL

#define led_control_OTADataParams_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            1) \
X(a, STATIC,   SINGULAR, BYTES,    chunk,             2)
#define led_control_OTADataParams_CALLBACK NULL
#define led_control_OTADataParams_DEFAULT NULL

#define led_control_OTARequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    cmd,               1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,start_params,params.start_params),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,data_params,params.data_params),  11)
#define led_control_OTARequest_CALLBACK NULL
#define led_control_OTARequest_DEFAULT NULL
#define led_control_OTARequest_params_start_params_MSGTYPE led_control_OTAStartParams
#define led_control_OTARequest_params_data_params_MSGTYPE led_control_OTADataParams

#define led_control_OTAResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1) \
X(a, STATIC,   SINGULAR, STRING,   error_msg,         2) \
X(a, STATIC,   SINGULAR, UINT32,   received_bytes,    3) \
X(a, STATIC,   SINGULAR, UINT32,   total_bytes,       4) \
X(a, STATIC,   SINGULAR, UINT32,   percent,           5) \
X(a, STATIC,   SINGULAR, BOOL,     done,              6)
#define led_control_OTAResponse_CALLBACK NULL
#define led_control_OTAResponse_DEFAULT NULL

#define led_control_PingRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   client_timestamp,   1)
#define led_control_PingRequest_CALLBACK NULL
#define led_control_PingRequest_DEFAULT NULL

#define led_control_PingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   client_timestamp,   1) \
X(a, STATIC,   SINGULAR, UINT64,   server_timestamp,   2)
#define led_control_PingResponse_CALLBACK NULL
#define led_control_PingResponse_DEFAULT NULL

#define led_control_FactoryResetRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   confirm_code,      1)
#define led_control_FactoryResetRequest_CALLBACK NULL
#define led_control_FactoryResetRequest_DEFAULT NULL

#define led_control_FactoryResetResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    error,             1)
#define led_control_FactoryResetResponse_CALLBACK NULL
#define led_control_FactoryResetResponse_DEFAULT NULL

#define led_control_Envelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   protocol_version,   1) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_device_info,payload.get_device_info),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_light_config,payload.set_light_config),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_channel_order,payload.set_channel_order),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scan_ic,payload.scan_ic),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_channel_mode,payload.set_channel_mode),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_on_off,payload.set_on_off),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_brightness,payload.set_brightness),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_color,payload.set_color),  32) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_static_mode,payload.set_static_mode),  33) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_preset_effect,payload.set_preset_effect),  34) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,scene_op,payload.scene_op),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,list_scenes,payload.list_scenes),  41) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ota,payload.ota),  50) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ping,payload.ping),  60) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,factory_reset,payload.factory_reset),  61) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,response,payload.response),  80) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,state_notify,payload.state_notify),  90)
#define led_control_Envelope_CALLBACK NULL
#define led_control_Envelope_DEFAULT NULL
#define led_control_Envelope_payload_get_device_info_MSGTYPE led_control_GetDeviceInfoRequest
#define led_control_Envelope_payload_set_light_config_MSGTYPE led_control_SetLightConfigRequest
#define led_control_Envelope_payload_set_channel_order_MSGTYPE led_control_SetCustomChannelOrderRequest
#define led_control_Envelope_payload_scan_ic_MSGTYPE led_control_ScanIcRequest
#define led_control_Envelope_payload_set_channel_mode_MSGTYPE led_control_SetChannelModeRequest
#define led_control_Envelope_payload_set_on_off_MSGTYPE led_control_SetOnOffRequest
#define led_control_Envelope_payload_set_brightness_MSGTYPE led_control_SetBrightnessRequest
#define led_control_Envelope_payload_set_color_MSGTYPE led_control_SetColorRequest
#define led_control_Envelope_payload_set_static_mode_MSGTYPE led_control_SetStaticModeRequest
#define led_control_Envelope_payload_set_preset_effect_MSGTYPE led_control_SetPresetEffectRequest
#define led_control_Envelope_payload_scene_op_MSGTYPE led_control_SceneOperationRequest
#define led_control_Envelope_payload_list_scenes_MSGTYPE led_control_ListScenesRequest
#define led_control_Envelope_payload_ota_MSGTYPE led_control_OTARequest
#define led_control_Envelope_payload_ping_MSGTYPE led_control_PingRequest
#define led_control_Envelope_payload_factory_reset_MSGTYPE led_control_FactoryResetRequest
#define led_control_Envelope_payload_response_MSGTYPE led_control_EnvelopeResponse
#define led_control_Envelope_payload_state_notify_MSGTYPE led_control_StateNotification

#define led_control_EnvelopeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   request_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    error,             2) \
X(a, STATIC,   SINGULAR, STRING,   error_msg,         3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,device_info_result,result.device_info_result),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,set_light_config,result.set_light_config),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,set_channel_order,result.set_channel_order),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,set_channel_mode_result,result.set_channel_mode_result),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,ic_scan_result,result.ic_scan_result),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,set_on_off_result,result.set_on_off_result),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,set_brightness_result,result.set_brightness_result),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,set_color_result,result.set_color_result),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,set_static_result,result.set_static_result),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,set_preset_result,result.set_preset_result),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,scene_op_result,result.scene_op_result),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,list_scenes_result,result.list_scenes_result),  31) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,ota_result,result.ota_result),  40) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,ping_result,result.ping_result),  50) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,factory_reset_result,result.factory_reset_result),  51)
#define led_control_EnvelopeResponse_CALLBACK NULL
#define led_control_EnvelopeResponse_DEFAULT NULL
#define led_control_EnvelopeResponse_result_device_info_result_MSGTYPE led_control_GetDeviceInfoResponse
#define led_control_EnvelopeResponse_result_set_light_config_MSGTYPE led_control_SetLightConfigResponse
#define led_control_EnvelopeResponse_result_set_channel_order_MSGTYPE led_control_SetCustomChannelOrderResponse
#define led_control_EnvelopeResponse_result_set_channel_mode_result_MSGTYPE led_control_SetChannelModeResponse
#define led_control_EnvelopeResponse_result_ic_scan_result_MSGTYPE led_control_IcScanResult
#define led_control_EnvelopeResponse_result_set_on_off_result_MSGTYPE led_control_SetOnOffResponse
#define led_control_EnvelopeResponse_result_set_brightness_result_MSGTYPE led_control_SetBrightnessResponse
#define led_control_EnvelopeResponse_result_set_color_result_MSGTYPE led_control_SetColorResponse
#define led_control_EnvelopeResponse_result_set_static_result_MSGTYPE led_control_SetStaticModeResponse
#define led_control_EnvelopeResponse_result_set_preset_result_MSGTYPE led_control_SetPresetEffectResponse
#define led_control_EnvelopeResponse_result_scene_op_result_MSGTYPE led_control_SceneOperationResponse
#define led_control_EnvelopeResponse_result_list_scenes_result_MSGTYPE led_control_ListScenesResponse
#define led_control_EnvelopeResponse_result_ota_result_MSGTYPE led_control_OTAResponse
#define led_control_EnvelopeResponse_result_ping_result_MSGTYPE led_control_PingResponse
#define led_control_EnvelopeResponse_result_factory_reset_result_MSGTYPE led_control_FactoryResetResponse

extern const pb_msgdesc_t led_control_ColorRGB_msg;
extern const pb_msgdesc_t led_control_ColorTemperature_msg;
extern const pb_msgdesc_t led_control_LightConfig_msg;
extern const pb_msgdesc_t led_control_DeviceInfo_msg;
extern const pb_msgdesc_t led_control_StaticState_msg;
extern const pb_msgdesc_t led_control_PresetEffect_msg;
extern const pb_msgdesc_t led_control_SegmentConfig_msg;
extern const pb_msgdesc_t led_control_CustomScene_msg;
extern const pb_msgdesc_t led_control_DeviceStatus_msg;
extern const pb_msgdesc_t led_control_GetDeviceInfoRequest_msg;
extern const pb_msgdesc_t led_control_GetDeviceInfoResponse_msg;
extern const pb_msgdesc_t led_control_SetLightConfigRequest_msg;
extern const pb_msgdesc_t led_control_SetLightConfigResponse_msg;
extern const pb_msgdesc_t led_control_SetCustomChannelOrderRequest_msg;
extern const pb_msgdesc_t led_control_SetCustomChannelOrderResponse_msg;
extern const pb_msgdesc_t led_control_ScanIcRequest_msg;
extern const pb_msgdesc_t led_control_IcScanResult_msg;
extern const pb_msgdesc_t led_control_SetChannelModeRequest_msg;
extern const pb_msgdesc_t led_control_SetChannelModeResponse_msg;
extern const pb_msgdesc_t led_control_SetOnOffRequest_msg;
extern const pb_msgdesc_t led_control_SetOnOffResponse_msg;
extern const pb_msgdesc_t led_control_SetBrightnessRequest_msg;
extern const pb_msgdesc_t led_control_SetBrightnessResponse_msg;
extern const pb_msgdesc_t led_control_SetColorRequest_msg;
extern const pb_msgdesc_t led_control_SetColorResponse_msg;
extern const pb_msgdesc_t led_control_SetStaticModeRequest_msg;
extern const pb_msgdesc_t led_control_SetStaticModeResponse_msg;
extern const pb_msgdesc_t led_control_SetPresetEffectRequest_msg;
extern const pb_msgdesc_t led_control_SetPresetEffectResponse_msg;
extern const pb_msgdesc_t led_control_SceneOperationRequest_msg;
extern const pb_msgdesc_t led_control_SceneOperationResponse_msg;
extern const pb_msgdesc_t led_control_ListScenesRequest_msg;
extern const pb_msgdesc_t led_control_ListScenesResponse_msg;
extern const pb_msgdesc_t led_control_SceneSummary_msg;
extern const pb_msgdesc_t led_control_StateNotification_msg;
extern const pb_msgdesc_t led_control_OTAStartParams_msg;
extern const pb_msgdesc_t led_control_OTADataParams_msg;
extern const pb_msgdesc_t led_control_OTARequest_msg;
extern const pb_msgdesc_t led_control_OTAResponse_msg;
extern const pb_msgdesc_t led_control_PingRequest_msg;
extern const pb_msgdesc_t led_control_PingResponse_msg;
extern const pb_msgdesc_t led_control_FactoryResetRequest_msg;
extern const pb_msgdesc_t led_control_FactoryResetResponse_msg;
extern const pb_msgdesc_t led_control_Envelope_msg;
extern const pb_msgdesc_t led_control_EnvelopeResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define led_control_ColorRGB_fields &led_control_ColorRGB_msg
#define led_control_ColorTemperature_fields &led_control_ColorTemperature_msg
#define led_control_LightConfig_fields &led_control_LightConfig_msg
#define led_control_DeviceInfo_fields &led_control_DeviceInfo_msg
#define led_control_StaticState_fields &led_control_StaticState_msg
#define led_control_PresetEffect_fields &led_control_PresetEffect_msg
#define led_control_SegmentConfig_fields &led_control_SegmentConfig_msg
#define led_control_CustomScene_fields &led_control_CustomScene_msg
#define led_control_DeviceStatus_fields &led_control_DeviceStatus_msg
#define led_control_GetDeviceInfoRequest_fields &led_control_GetDeviceInfoRequest_msg
#define led_control_GetDeviceInfoResponse_fields &led_control_GetDeviceInfoResponse_msg
#define led_control_SetLightConfigRequest_fields &led_control_SetLightConfigRequest_msg
#define led_control_SetLightConfigResponse_fields &led_control_SetLightConfigResponse_msg
#define led_control_SetCustomChannelOrderRequest_fields &led_control_SetCustomChannelOrderRequest_msg
#define led_control_SetCustomChannelOrderResponse_fields &led_control_SetCustomChannelOrderResponse_msg
#define led_control_ScanIcRequest_fields &led_control_ScanIcRequest_msg
#define led_control_IcScanResult_fields &led_control_IcScanResult_msg
#define led_control_SetChannelModeRequest_fields &led_control_SetChannelModeRequest_msg
#define led_control_SetChannelModeResponse_fields &led_control_SetChannelModeResponse_msg
#define led_control_SetOnOffRequest_fields &led_control_SetOnOffRequest_msg
#define led_control_SetOnOffResponse_fields &led_control_SetOnOffResponse_msg
#define led_control_SetBrightnessRequest_fields &led_control_SetBrightnessRequest_msg
#define led_control_SetBrightnessResponse_fields &led_control_SetBrightnessResponse_msg
#define led_control_SetColorRequest_fields &led_control_SetColorRequest_msg
#define led_control_SetColorResponse_fields &led_control_SetColorResponse_msg
#define led_control_SetStaticModeRequest_fields &led_control_SetStaticModeRequest_msg
#define led_control_SetStaticModeResponse_fields &led_control_SetStaticModeResponse_msg
#define led_control_SetPresetEffectRequest_fields &led_control_SetPresetEffectRequest_msg
#define led_control_SetPresetEffectResponse_fields &led_control_SetPresetEffectResponse_msg
#define led_control_SceneOperationRequest_fields &led_control_SceneOperationRequest_msg
#define led_control_SceneOperationResponse_fields &led_control_SceneOperationResponse_msg
#define led_control_ListScenesRequest_fields &led_control_ListScenesRequest_msg
#define led_control_ListScenesResponse_fields &led_control_ListScenesResponse_msg
#define led_control_SceneSummary_fields &led_control_SceneSummary_msg
#define led_control_StateNotification_fields &led_control_StateNotification_msg
#define led_control_OTAStartParams_fields &led_control_OTAStartParams_msg
#define led_control_OTADataParams_fields &led_control_OTADataParams_msg
#define led_control_OTARequest_fields &led_control_OTARequest_msg
#define led_control_OTAResponse_fields &led_control_OTAResponse_msg
#define led_control_PingRequest_fields &led_control_PingRequest_msg
#define led_control_PingResponse_fields &led_control_PingResponse_msg
#define led_control_FactoryResetRequest_fields &led_control_FactoryResetRequest_msg
#define led_control_FactoryResetResponse_fields &led_control_FactoryResetResponse_msg
#define led_control_Envelope_fields &led_control_Envelope_msg
#define led_control_EnvelopeResponse_fields &led_control_EnvelopeResponse_msg

/* Maximum encoded size of messages (where known) */
/* led_control_SetCustomChannelOrderRequest_size depends on runtime parameters */
/* led_control_Envelope_size depends on runtime parameters */
#define LED_CONTROL_LED_CONTROL_PB_H_MAX_SIZE    led_control_EnvelopeResponse_size
#define led_control_ColorRGB_size                18
#define led_control_ColorTemperature_size        6
#define led_control_CustomScene_size             392
#define led_control_DeviceInfo_size              148
#define led_control_DeviceStatus_size            395
#define led_control_EnvelopeResponse_size        2382
#define led_control_FactoryResetRequest_size     6
#define led_control_FactoryResetResponse_size    2
#define led_control_GetDeviceInfoRequest_size    0
#define led_control_GetDeviceInfoResponse_size   589
#define led_control_IcScanResult_size            6
#define led_control_LightConfig_size             38
#define led_control_ListScenesRequest_size       0
#define led_control_ListScenesResponse_size      1344
#define led_control_OTADataParams_size           1009
#define led_control_OTARequest_size              1014
#define led_control_OTAResponse_size             88
#define led_control_OTAStartParams_size          18
#define led_control_PingRequest_size             11
#define led_control_PingResponse_size            22
#define led_control_PresetEffect_size            8
#define led_control_ScanIcRequest_size           0
#define led_control_SceneOperationRequest_size   403
#define led_control_SceneOperationResponse_size  68
#define led_control_SceneSummary_size            40
#define led_control_SegmentConfig_size           32
#define led_control_SetBrightnessRequest_size    6
#define led_control_SetBrightnessResponse_size   2
#define led_control_SetChannelModeRequest_size   10
#define led_control_SetChannelModeResponse_size  68
#define led_control_SetColorRequest_size         42
#define led_control_SetColorResponse_size        2
#define led_control_SetCustomChannelOrderResponse_size 68
#define led_control_SetLightConfigRequest_size   40
#define led_control_SetLightConfigResponse_size  70
#define led_control_SetOnOffRequest_size         2
#define led_control_SetOnOffResponse_size        2
#define led_control_SetPresetEffectRequest_size  14
#define led_control_SetPresetEffectResponse_size 2
#define led_control_SetStaticModeRequest_size    36
#define led_control_SetStaticModeResponse_size   2
#define led_control_StateNotification_size       457
#define led_control_StaticState_size             44

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
