/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "led_control.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(led_control_ColorRGB, led_control_ColorRGB, AUTO)


PB_BIND(led_control_ColorTemperature, led_control_ColorTemperature, AUTO)


PB_BIND(led_control_LightConfig, led_control_LightConfig, AUTO)


PB_BIND(led_control_DeviceInfo, led_control_DeviceInfo, AUTO)


PB_BIND(led_control_StaticState, led_control_StaticState, AUTO)


PB_BIND(led_control_PresetEffect, led_control_PresetEffect, AUTO)


PB_BIND(led_control_SegmentConfig, led_control_SegmentConfig, AUTO)


PB_BIND(led_control_CustomScene, led_control_CustomScene, 2)


PB_BIND(led_control_DeviceStatus, led_control_DeviceStatus, 2)


PB_BIND(led_control_GetDeviceInfoRequest, led_control_GetDeviceInfoRequest, AUTO)


PB_BIND(led_control_GetDeviceInfoResponse, led_control_GetDeviceInfoResponse, 2)


PB_BIND(led_control_SetLightConfigRequest, led_control_SetLightConfigRequest, AUTO)


PB_BIND(led_control_SetLightConfigResponse, led_control_SetLightConfigResponse, AUTO)


PB_BIND(led_control_SetCustomChannelOrderRequest, led_control_SetCustomChannelOrderRequest, AUTO)


PB_BIND(led_control_SetCustomChannelOrderResponse, led_control_SetCustomChannelOrderResponse, AUTO)


PB_BIND(led_control_ScanIcRequest, led_control_ScanIcRequest, AUTO)


PB_BIND(led_control_IcScanResult, led_control_IcScanResult, AUTO)


PB_BIND(led_control_SetChannelModeRequest, led_control_SetChannelModeRequest, AUTO)


PB_BIND(led_control_SetChannelModeResponse, led_control_SetChannelModeResponse, AUTO)


PB_BIND(led_control_SetOnOffRequest, led_control_SetOnOffRequest, AUTO)


PB_BIND(led_control_SetOnOffResponse, led_control_SetOnOffResponse, AUTO)


PB_BIND(led_control_SetBrightnessRequest, led_control_SetBrightnessRequest, AUTO)


PB_BIND(led_control_SetBrightnessResponse, led_control_SetBrightnessResponse, AUTO)


PB_BIND(led_control_SetColorRequest, led_control_SetColorRequest, AUTO)


PB_BIND(led_control_SetColorResponse, led_control_SetColorResponse, AUTO)


PB_BIND(led_control_SetStaticModeRequest, led_control_SetStaticModeRequest, AUTO)


PB_BIND(led_control_SetStaticModeResponse, led_control_SetStaticModeResponse, AUTO)


PB_BIND(led_control_SetPresetEffectRequest, led_control_SetPresetEffectRequest, AUTO)


PB_BIND(led_control_SetPresetEffectResponse, led_control_SetPresetEffectResponse, AUTO)


PB_BIND(led_control_SceneOperationRequest, led_control_SceneOperationRequest, 2)


PB_BIND(led_control_SceneOperationResponse, led_control_SceneOperationResponse, AUTO)


PB_BIND(led_control_ListScenesRequest, led_control_ListScenesRequest, AUTO)


PB_BIND(led_control_ListScenesResponse, led_control_ListScenesResponse, 2)


PB_BIND(led_control_SceneSummary, led_control_SceneSummary, AUTO)


PB_BIND(led_control_StateNotification, led_control_StateNotification, 2)


PB_BIND(led_control_OTAStartParams, led_control_OTAStartParams, AUTO)


PB_BIND(led_control_OTADataParams, led_control_OTADataParams, 2)


PB_BIND(led_control_OTARequest, led_control_OTARequest, 2)


PB_BIND(led_control_OTAResponse, led_control_OTAResponse, AUTO)


PB_BIND(led_control_PingRequest, led_control_PingRequest, AUTO)


PB_BIND(led_control_PingResponse, led_control_PingResponse, AUTO)


PB_BIND(led_control_FactoryResetRequest, led_control_FactoryResetRequest, AUTO)


PB_BIND(led_control_FactoryResetResponse, led_control_FactoryResetResponse, AUTO)


PB_BIND(led_control_Envelope, led_control_Envelope, 2)


PB_BIND(led_control_EnvelopeResponse, led_control_EnvelopeResponse, 2)



















